version: '3.8'

services:
  # Serviço principal (frontend + API)
  book-donation-app:
    build: .
    container_name: book-donation-app
    ports:
      - "5000:5000"
    volumes:
      # Persist database
      - book_data:/app/src/database
    restart: unless-stopped
    # Health check via HTTP request (requires curl in container)
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:5000/"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s

  # Serviço de administração
  book-donation-admin:
    build: .
    container_name: book-donation-admin
    ports:
      - "5001:5001"
    volumes:
      # Compartilhar o mesmo banco de dados
      - book_data:/app/src/database
    restart: unless-stopped
    command: ["python", "src/admin_app.py"]

volumes:
  book_data:

